const base = window.DASHBOARD_DATA, cube = window.DASHBOARD_DATA_V2;
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const params = new URLSearchParams(location.search), MAX = cube.meta.maxDate, MIN = cube.meta.minDate;
const state = {section:params.get('view')||'overview', range:params.get('range')||'7d', start:params.get('start'), end:params.get('end'), shop:params.get('shop')||'all', line:params.get('line')||'all', sku:params.get('sku')||null, risk:'all', metric:'gmv', query:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v)||0, integer=v=>Math.round(v).toLocaleString('zh-CN'), pct=v=>`${(v*100).toFixed(1)}%`;
const money=(v,compact=true)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',notation:compact?'compact':'standard',maximumFractionDigits:compact?1:0}).format(v||0);
const iso=d=>d.toISOString().slice(0,10), parse=s=>new Date(`${s}T12:00:00`), add=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+n);return iso(d)};

function resolveDates(){let end=state.end||MAX,start=state.start;if(state.range==='yesterday'){start=end=MAX}else if(state.range==='3d'){end=MAX;start=add(end,-2)}else if(state.range==='7d'){end=MAX;start=add(end,-6)}else if(state.range==='week'){end=MAX;const d=parse(end),shift=(d.getDay()+6)%7;start=add(end,-shift)}else{start=start||add(MAX,-6);end=end||MAX}if(start<MIN)start=MIN;if(end>MAX)end=MAX;if(start>end)[start,end]=[end,start];state.start=start;state.end=end;return{start,end}}
function within(r){return r.date>=state.start&&r.date<=state.end&&(state.shop==='all'||r.shop===state.shop)&&(state.line==='all'||r.line===state.line)&&(!state.sku||r.sku===state.sku)}
function rows(){return cube.dailySku.filter(within)}
function aggregate(list,key){const m=new Map();list.forEach(r=>{const id=r[key],x=m.get(id)||{id,name:key==='sku'?r.name:id,line:r.line,sku:r.sku,gmv:0,visitors:0,buyers:0,orders:0,units:0,cart:0,spend:0,adRevenue:0,clicks:0,impressions:0};['gmv','visitors','buyers','orders','units','cart','spend','adRevenue','clicks','impressions'].forEach(k=>x[k]+=num(r[k]));m.set(id,x)});return[...m.values()]}
function totals(list){return aggregate(list,'_all')[0]||{gmv:0,visitors:0,buyers:0,orders:0,units:0,cart:0,spend:0,adRevenue:0,clicks:0,impressions:0}}
function syncUrl(){const q=new URLSearchParams();if(state.section!=='overview')q.set('view',state.section);q.set('range',state.range);q.set('start',state.start);q.set('end',state.end);if(state.shop!=='all')q.set('shop',state.shop);if(state.line!=='all')q.set('line',state.line);if(state.sku)q.set('sku',state.sku);if(state.compareMode)q.set('compare',state.compareMode==='period'?'period':'yoy');history.replaceState({},'',`${location.pathname}?${q}`)}
function setView(){const names={overview:'经营总览',sales:'销售下钻',ads:'投放效率',inventory:'货品监控'},notes={overview:'京东渠道 · 日级 SKU 数据',sales:'类目与 SKU 销售表现',ads:'投放效率与关键词分析',inventory:'库存快照 · 补货与周转预警'};$('h1').textContent=names[state.section];const eyebrow=$('.eyebrow');if(eyebrow)eyebrow.textContent=notes[state.section];const search=$('#globalSearch');if(search)search.placeholder=state.section==='inventory'?'搜索库存 SKU / 货品':'搜索 SKU / 货品';$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===state.section));$$('[data-view]').forEach(e=>e.hidden=!e.dataset.view.split(' ').includes(state.section))}function renderDate(){resolveDates();$$('#quickDates button').forEach(b=>b.classList.toggle('active',b.dataset.range===state.range));$('#customDates').hidden=state.range!=='custom';$('#startDate').value=state.start;$('#endDate').value=state.end;$('#startDate').min=$('#endDate').min=MIN;$('#startDate').max=$('#endDate').max=MAX;$('#dateText').textContent=`${state.start.replaceAll('-','.')} — ${state.end.replaceAll('-','.')}`;const days=Math.round((parse(state.end)-parse(state.start))/86400000)+1;$('#coverageText').textContent=`${days} 天 · 数据截至 ${MAX}`}
function renderBreadcrumb(){let html='<button data-level="all">全部品线</button>';if(state.line!=='all')html+=`<span>›</span><button data-level="line">${esc(state.line)}</button>`;if(state.sku){const item=cube.skuIndex.find(x=>x.sku===state.sku);html+=`<span>›</span><button data-level="sku">${esc(item?.name||state.sku)}</button>`}$('#breadcrumb').innerHTML=html;$$('#breadcrumb button').forEach(b=>b.onclick=()=>{if(b.dataset.level==='all'){state.line='all';state.sku=null}else if(b.dataset.level==='line')state.sku=null;renderAll()})}
function renderFilters(){const f=[];if(state.shop!=='all')f.push(`店铺：${state.shop}`);if(state.line!=='all')f.push(`品线：${state.line}`);if(state.sku)f.push(`SKU：${state.sku}`);$('#activeFilters').innerHTML=f.map(x=>`<span class="filter-chip">${esc(x)}</span>`).join('');$('#filterCount').textContent=f.length}
function renderKpis(list){const t=totals(list),roi=t.spend?t.adRevenue/t.spend:0,conv=t.visitors?t.buyers/t.visitors:0,ctr=t.impressions?t.clicks/t.impressions:0,fee=t.gmv?t.spend/t.gmv:0;const cards=[['GMV',money(t.gmv),`${integer(t.orders)} 单`,'↗'],['访客数',integer(t.visitors),`成交 ${integer(t.buyers)} 人`,'◉'],['成交转化率',pct(conv),`加购 ${integer(t.cart)} 人`,'⌁'],['投放花费',money(t.spend),`CTR ${pct(ctr)}`,'◎'],['投放 ROI',roi.toFixed(2),`广告成交 ${money(t.adRevenue)}`,'◔'],['费比',pct(fee),'投放花费 / GMV','%']];$('#kpiGrid').innerHTML=cards.map(c=>`<article class="kpi-card"><div class="kpi-top"><span>${c[0]}</span><i class="kpi-icon">${c[3]}</i></div><strong>${c[1]}</strong><span class="delta ${c[0]==='投放 ROI'&&roi<1.5?'down':'up'}">${c[2]}</span></article>`).join('');const top=aggregate(list,'line').sort((a,b)=>b.gmv-a.gmv)[0];$('#insightTitle').textContent=t.gmv?`${top?.id||'当前范围'}贡献领先，投放 ROI ${roi.toFixed(2)}`:'当前范围暂无经营数据';$('#insightText').textContent=t.gmv?`所选时段 GMV ${money(t.gmv,false)}，成交 ${integer(t.orders)} 单，${t.spend?`投放花费 ${money(t.spend,false)}`:'暂无投放记录'}。`:`请调整日期、店铺或品线筛选。`}

function trend(list,target='#salesChart'){
  const daily=aggregate(list,'date').sort((a,b)=>a.id.localeCompare(b.id)),host=$(target);
  if(!daily.length){host.innerHTML='<div class="empty-state">当前范围暂无数据</div>';return}
  const W=760,H=250,p={l:55,r:20,t:15,b:34},max=Math.max(...daily.map(x=>x.gmv),1)*1.1,maxSpend=Math.max(...daily.map(x=>x.spend),1)*1.1;
  const x=i=>p.l+(daily.length===1?(W-p.l-p.r)/2:i*(W-p.l-p.r)/(daily.length-1)),y=v=>H-p.b-v/max*(H-p.t-p.b),ys=v=>H-p.b-v/maxSpend*(H-p.t-p.b);
  const path=(k,fn)=>daily.map((d,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${fn(d[k]).toFixed(1)}`).join(' ');
  host.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="每日 GMV 与投放花费趋势">${[0,.25,.5,.75,1].map(t=>`<line class="grid-line" x1="${p.l}" x2="${W-p.r}" y1="${y(max*t)}" y2="${y(max*t)}"/><text class="axis-text" x="3" y="${y(max*t)+4}">${money(max*t)}</text>`).join('')}<path d="${path('spend',ys)}" fill="none" stroke="#aab5ae" stroke-width="2" stroke-dasharray="5 5"/><path d="${path('gmv',y)}" fill="none" stroke="#145c3e" stroke-width="3"/>${daily.map((d,i)=>`<g class="trend-point" tabindex="0" role="button" aria-label="${d.id}，GMV ${money(d.gmv,false)}，投放花费 ${money(d.spend,false)}" data-date="${d.id}" data-gmv="${d.gmv}" data-spend="${d.spend}"><circle class="trend-hit" cx="${x(i)}" cy="${y(d.gmv)}" r="13"/><circle class="trend-dot" cx="${x(i)}" cy="${y(d.gmv)}" r="5"/></g>${i%Math.max(1,Math.ceil(daily.length/7))===0?`<text class="axis-text" x="${x(i)}" y="${H-8}" text-anchor="middle">${d.id.slice(5)}</text>`:''}`).join('')}</svg><div class="trend-tooltip" role="status" aria-live="polite"></div>`;
  const tip=host.querySelector('.trend-tooltip');
  const show=(point,event)=>{host.querySelectorAll('.trend-point.active').forEach(x=>x.classList.remove('active'));point.classList.add('active');tip.innerHTML=`<strong>${esc(point.dataset.date)}</strong><span><i class="gmv"></i>GMV <b>${money(point.dataset.gmv,false)}</b></span><span><i class="spend"></i>投放花费 <b>${money(point.dataset.spend,false)}</b></span>`;tip.classList.add('show');const box=host.getBoundingClientRect(),left=event?.clientX?event.clientX-box.left:point.getBoundingClientRect().left-box.left,top=event?.clientY?event.clientY-box.top:point.getBoundingClientRect().top-box.top;tip.style.left=Math.max(8,Math.min(box.width-tip.offsetWidth-8,left+12))+'px';tip.style.top=Math.max(8,top-tip.offsetHeight-10)+'px'};
  const hide=point=>{point.classList.remove('active');tip.classList.remove('show')};
  host.querySelectorAll('.trend-point').forEach(point=>{point.addEventListener('pointerenter',e=>show(point,e));point.addEventListener('pointermove',e=>show(point,e));point.addEventListener('pointerleave',()=>hide(point));point.addEventListener('focus',e=>show(point,e));point.addEventListener('blur',()=>hide(point));point.addEventListener('click',e=>{e.stopPropagation();show(point,e)})});
}function renderLines(list){const lines=aggregate(list,'line').sort((a,b)=>b.gmv-a.gmv),max=Math.max(...lines.map(x=>x.gmv),1);$('#lineRanking').innerHTML=lines.map(d=>`<button class="drill-row" data-line="${esc(d.id)}"><strong>${esc(d.id)}</strong><span class="mini-track"><i style="width:${d.gmv/max*100}%"></i></span><span class="value">${money(d.gmv)}</span></button>`).join('')||'<div class="empty-state">暂无品线数据</div>';$$('.drill-row').forEach(b=>b.onclick=()=>{state.line=b.dataset.line;state.sku=null;renderAll();$('#skuRanking').scrollIntoView({behavior:'smooth',block:'center'})})}
function metricValue(d){return state.metric==='roi'?(d.spend?d.adRevenue/d.spend:0):d[state.metric]}
function renderSku(list){let skus=aggregate(list,'sku').filter(x=>!state.query||`${x.name}${x.sku}`.toLowerCase().includes(state.query)).sort((a,b)=>metricValue(b)-metricValue(a)).slice(0,20);$('#skuRanking').innerHTML=skus.map((d,i)=>`<button class="sku-row" data-sku="${esc(d.sku)}"><span class="rank-num">${String(i+1).padStart(2,'0')}</span><span class="sku-name"><strong>${esc(d.name)}</strong><small>${esc(d.sku)}</small></span><span class="line">${esc(d.line)}</span><span class="metric">${state.metric==='roi'?metricValue(d).toFixed(2):state.metric==='gmv'?money(d.gmv):money(d.spend)}</span></button>`).join('')||'<div class="empty-state">没有匹配的 SKU</div>';$$('.sku-row').forEach(b=>b.onclick=()=>{state.sku=b.dataset.sku;const s=skus.find(x=>x.sku===state.sku);if(state.line==='all'&&s)state.line=s.line;renderAll();$('#skuDetail').scrollIntoView({behavior:'smooth',block:'start'})});renderMatrix(skus)}
function renderMatrix(skus){const pts=skus.filter(x=>x.spend>0).slice(0,30);if(!pts.length){$('#skuMatrix').innerHTML='<div class="empty-state">当前范围暂无 SKU 投放数据</div>';return}const W=620,H=230,p={l:45,r:25,t:18,b:32},mx=Math.max(...pts.map(x=>x.spend),1)*1.1,my=Math.max(...pts.map(x=>x.adRevenue/x.spend),1)*1.15,x=v=>p.l+v/mx*(W-p.l-p.r),y=v=>H-p.b-v/my*(H-p.t-p.b);$('#skuMatrix').innerHTML=`<svg viewBox="0 0 ${W} ${H}">${[0,.25,.5,.75,1].map(t=>`<line class="grid-line" x1="${p.l}" x2="${W-p.r}" y1="${y(my*t)}" y2="${y(my*t)}"/><text class="axis-text" x="5" y="${y(my*t)+3}">${(my*t).toFixed(1)}</text>`).join('')}<text class="axis-text" x="${W/2}" y="${H-5}">投放花费 →</text>${pts.map(d=>{const roi=d.adRevenue/d.spend;return`<circle cx="${x(d.spend)}" cy="${y(roi)}" r="${6+Math.min(8,Math.sqrt(d.gmv/5000))}" fill="${roi<1.5?'#c7483a':'#2f8a5d'}" opacity=".82" data-sku="${esc(d.sku)}"><title>${esc(d.name)} · 花费 ${money(d.spend,false)} · ROI ${roi.toFixed(2)}</title></circle>`}).join('')}</svg>`;$$('#skuMatrix circle').forEach(c=>c.onclick=()=>{state.sku=c.dataset.sku;renderAll();$('#skuDetail').scrollIntoView({behavior:'smooth'})})}
function renderDetail(list){const panel=$('#skuDetail');if(!state.sku){panel.hidden=true;return}panel.hidden=false;const t=totals(list),item=cube.skuIndex.find(x=>x.sku===state.sku),roi=t.spend?t.adRevenue/t.spend:0,conv=t.visitors?t.buyers/t.visitors:0,cpc=t.clicks?t.spend/t.clicks:null;$('#skuDetailTitle').textContent=`${item?.name||state.sku} · ${state.sku}`;$('#detailKpis').innerHTML=[['GMV',money(t.gmv)],['成交单量',integer(t.orders)],['访客',integer(t.visitors)],['转化率',pct(conv)],['投放花费',money(t.spend)],['ROI',roi.toFixed(2)],['CPC',cpc==null?'-':money(cpc)]].map(x=>`<div class="detail-kpi"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');trend(list,'#skuDaily');const inv=base.inventory.find(x=>x.sku===state.sku),notes=[];notes.push([roi>=2?'good':roi>=1?'warn':'bad','投放效率',t.spend?`ROI ${roi.toFixed(2)}，广告成交 ${money(t.adRevenue,false)}`:'当前时段无投放记录']);notes.push([conv>=.1?'good':conv>=.05?'warn':'bad','成交转化',`访客转化率 ${pct(conv)}，成交 ${integer(t.buyers)} 人`]);notes.push([inv?(inv.replenish>0?'bad':inv.days>60?'warn':'good'):'warn','库存衔接',inv?`现货 ${integer(inv.stock)}，在途 ${integer(inv.inTransit)}，建议补货 ${integer(inv.replenish)}`:'库存表中未找到同 SKU']);$('#skuDiagnosis').innerHTML=notes.map(n=>`<div class="diagnosis-item"><i class="${n[0]}"></i><div><strong>${n[1]}</strong><small>${n[2]}</small></div></div>`).join('')}
function riskOf(d){return d.replenish>0?'red':d.days>60?'amber':'green'}
function renderInventory(){
  let all=base.inventory.filter(d=>(state.shop==='all'||d.shop.includes(state.shop))&&(!state.sku||d.sku===state.sku)&&(!state.query||`${d.name}${d.sku}`.toLowerCase().includes(state.query))),rs=all;
  if(state.risk==='urgent')rs=rs.filter(d=>d.replenish>0);if(state.risk==='slow')rs=rs.filter(d=>d.days>60);rs=rs.slice(0,12);
  const badge=d=>riskOf(d)==='red'?['red','需补货']:riskOf(d)==='amber'?['amber','高周转']:['green','平稳'];
  const summary=$('#inventorySummary');if(summary){const total=base.inventorySummary||{},urgent=all.filter(d=>d.replenish>0).length;summary.innerHTML=[['库存 SKU',integer(total.skuCount||all.length),urgent?`${urgent} 个需补货`:'暂无补货预警','▦'],['现货数量',integer(total.stock||all.reduce((a,d)=>a+num(d.stock),0)),'当前库存快照','□'],['库存金额',money(total.stockValue||all.reduce((a,d)=>a+num(d.stockValue),0)),'库存资金占用','¥'],['在途数量',integer(total.transit||all.reduce((a,d)=>a+num(d.inTransit),0)),'在途库存','→'],['建议补货',integer(total.replenish||all.reduce((a,d)=>a+Math.max(0,num(d.replenish)),0)),'建议补货总量','!']].map((c,i)=>`<article class="kpi-card inventory-kpi ${i===4&&num(total.replenish)>0?'warning':''}"><div class="kpi-top"><span>${c[0]}</span><i class="kpi-icon">${c[3]}</i></div><strong>${c[1]}</strong><span class="delta ${i===4&&num(total.replenish)>0?'down':'up'}">${c[2]}</span></article>`).join('')}
  $('#inventoryBody').innerHTML=rs.map(d=>{const b=badge(d);return`<tr><td>${esc(d.name)}<br><small>${esc(d.sku)}</small></td><td>${esc(d.shop)}</td><td>${integer(d.stock)}</td><td>${integer(d.inTransit)}</td><td>${integer(d.sales30)}</td><td>${d.days?d.days.toFixed(1):'-'}</td><td>${integer(d.replenish)}</td><td><span class="badge ${b[0]}">${b[1]}</span></td></tr>`}).join('')||'<tr><td colspan="8">库存表中没有匹配记录</td></tr>';
  $('#inventoryCards').innerHTML=rs.map(d=>{const b=badge(d);return`<article class="inventory-card"><div class="title"><div><h4>${esc(d.name)}</h4><small>${esc(d.shop)} · ${esc(d.sku)}</small></div><span class="badge ${b[0]}">${b[1]}</span></div><dl><div><dt>现货</dt><dd>${integer(d.stock)}</dd></div><div><dt>在途</dt><dd>${integer(d.inTransit)}</dd></div><div><dt>建议补货</dt><dd>${integer(d.replenish)}</dd></div></dl></article>`}).join('')
}function renderAll(){resolveDates();const list=rows();renderDate();renderBreadcrumb();renderFilters();renderKpis(list);trend(list);renderLines(list);renderSku(list);renderDetail(list);renderInventory();setView();syncUrl()}
function drawer(open){$('#filterDrawer').classList.toggle('open',open);$('#drawerBackdrop').classList.toggle('open',open);$('#filterDrawer').setAttribute('aria-hidden',String(!open))}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1600)}
function init(){[...new Set(cube.skuIndex.map(x=>x.line))].sort().forEach(v=>$('#lineFilter').insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`));$('#shopFilter').value=state.shop;$('#lineFilter').value=state.line;$$('.nav-item').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;setView();syncUrl();scrollTo({top:0,behavior:'smooth'})});$$('#quickDates button').forEach(b=>b.onclick=()=>{state.range=b.dataset.range;if(state.range!=='custom'){state.start=state.end=null;renderAll()}else renderDate()});$('#applyDate').onclick=()=>{state.range='custom';state.start=$('#startDate').value;state.end=$('#endDate').value;renderAll()};$('#filterBtn').onclick=()=>drawer(true);$('#closeDrawer').onclick=$('#drawerBackdrop').onclick=()=>drawer(false);$('#applyFilters').onclick=()=>{state.shop=$('#shopFilter').value;state.line=$('#lineFilter').value;state.sku=null;drawer(false);renderAll()};$('#resetFilters').onclick=()=>{state.shop=state.line='all';state.sku=null;$('#shopFilter').value=$('#lineFilter').value='all';renderAll()};$('#globalSearch').oninput=e=>{state.query=e.target.value.trim().toLowerCase();renderSku(rows());renderInventory()};$$('#skuMetric button').forEach(b=>b.onclick=()=>{$$('#skuMetric button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.metric=b.dataset.metric;renderSku(rows())});$$('#riskFilter button').forEach(b=>b.onclick=()=>{$$('#riskFilter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.risk=b.dataset.risk;renderInventory()});$('#closeSku').onclick=()=>{state.sku=null;renderAll()};$('#exportBtn').onclick=()=>{toast('正在打开打印 / PDF 导出');setTimeout(()=>print(),220)};renderAll()}
init();
