(function bootHierarchy(attempt=0){
  if(!document.querySelector('#lineMulti')){if(attempt<30)setTimeout(()=>bootHierarchy(attempt+1),50);return}
  if(document.querySelector('#ketoconazoleParent'))return;
  const KIDS=['酮康唑 OTC','酮康唑 RX'], isKet=x=>KIDS.includes(x), otherLines=[...new Set(cube.skuIndex.map(x=>x.line))].filter(x=>!isKet(x)).sort();
  state.categoryFocus=new URLSearchParams(location.search).get('focus')||null;
  const multi=$('#lineMulti');
  multi.innerHTML=`<div class="multi-actions"><button type="button" data-tree="all">全选</button><button type="button" data-tree="clear">清空</button></div><label class="tree-parent"><input id="ketoconazoleParent" type="checkbox" value="酮康唑"><span>酮康唑 <small>OTC + RX</small></span></label>${KIDS.map(x=>`<label class="tree-child"><input type="checkbox" value="${esc(x)}"><span>${esc(x)}</span></label>`).join('')}${otherLines.map(x=>`<label><input type="checkbox" value="${esc(x)}"><span>${esc(x)}</span></label>`).join('')}`;

  function leafChecks(){return $$('#lineMulti input').filter(x=>x.id!=='ketoconazoleParent')}
  function chosen(){return leafChecks().filter(x=>x.checked).map(x=>x.value)}
  function syncTree(){leafChecks().forEach(x=>x.checked=state.lines.includes(x.value));const count=KIDS.filter(x=>state.lines.includes(x)).length,p=$('#ketoconazoleParent');p.checked=count===2;p.indeterminate=count===1}
  function refreshSkuTree(){const q=$('#skuSearch').value.trim().toLowerCase(),selected=state.sku||$('#skuFilter').value||'all',filter=chosen();const list=cube.skuIndex.filter(x=>(!filter.length||filter.includes(x.line))&&(!q||`${x.name}${x.sku}`.toLowerCase().includes(q))).slice(0,160);$('#skuFilter').innerHTML=`<option value="all">全部 SKU（${list.length}）</option>`+list.map(x=>`<option value="${esc(x.sku)}">${esc(x.line)}｜${esc(x.name)} · ${esc(x.sku)}</option>`).join('');if([...$('#skuFilter').options].some(o=>o.value===selected))$('#skuFilter').value=selected}
  function groupRoot(list){const map=new Map();list.forEach(r=>{const id=isKet(r.line)?'酮康唑':r.line,x=map.get(id)||{id,name:id,line:id,gmv:0,visitors:0,buyers:0,orders:0,units:0,cart:0,spend:0,adRevenue:0,clicks:0,impressions:0};['gmv','visitors','buyers','orders','units','cart','spend','adRevenue','clicks','impressions'].forEach(k=>x[k]+=num(r[k]));map.set(id,x)});return[...map.values()]}
  function drawRank(items,child=false){const max=Math.max(...items.map(x=>x.gmv),1);$('#lineRanking').innerHTML=items.sort((a,b)=>b.gmv-a.gmv).map(d=>`<button class="drill-row ${child?'child-category':''}" data-category="${esc(d.id)}"><strong>${child?'↳ ':''}${esc(d.id)}${d.id==='酮康唑'?' <small>OTC + RX</small>':''}</strong><span class="mini-track"><i style="width:${d.gmv/max*100}%"></i></span><span class="value">${money(d.gmv)}</span></button>`).join('')||'<div class="empty-state">暂无类目数据</div>';$$('.drill-row').forEach(b=>b.onclick=()=>{const c=b.dataset.category;if(c==='酮康唑'){state.categoryFocus='酮康唑';state.lines=KIDS.slice()}else if(isKet(c)){state.lines=[c];state.categoryFocus='酮康唑'}else{state.lines=[c];state.categoryFocus=null}state.sku=null;syncTree();refreshSkuTree();renderAll()})}

  renderLines=function(list){if(state.categoryFocus==='酮康唑')drawRank(aggregate(list.filter(r=>isKet(r.line)),'line'),true);else drawRank(groupRoot(list),false)};
  renderBreadcrumb=function(){let html='<button data-level="all">全部类目</button>';if(state.categoryFocus==='酮康唑')html+='<span>›</span><button data-level="parent">酮康唑</button>';else if(state.lines.length){const both=KIDS.every(x=>state.lines.includes(x))&&state.lines.filter(isKet).length===2;html+=`<span>›</span><strong>${both?'酮康唑（OTC + RX）':state.lines.map(esc).join(' + ')}</strong>`}if(state.sku){const item=cube.skuIndex.find(x=>x.sku===state.sku);html+=`<span>›</span><strong>${esc(item?.name||state.sku)}</strong>`}$('#breadcrumb').innerHTML=html;const back=$('#backLevel');back.hidden=!state.lines.length&&!state.sku&&!state.categoryFocus;back.textContent=state.sku?'← 返回所属类目':state.categoryFocus?'← 返回全部类目':'← 清除类目筛选';back.onclick=()=>{if(state.sku)state.sku=null;else if(state.categoryFocus){state.categoryFocus=null;state.lines=[]}else state.lines=[];syncTree();refreshSkuTree();renderAll()};$('#breadcrumb [data-level="all"]').onclick=()=>{state.categoryFocus=null;state.lines=[];state.sku=null;syncTree();refreshSkuTree();renderAll()};const parent=$('#breadcrumb [data-level="parent"]');if(parent)parent.onclick=()=>{state.sku=null;state.lines=KIDS.slice();syncTree();refreshSkuTree();renderAll()}};
  renderFilters=function(){const chips=[];if(state.shop!=='all')chips.push({key:'shop',label:`店铺：${state.shop}`});const hasBoth=KIDS.every(x=>state.lines.includes(x));if(hasBoth)chips.push({key:'ket',label:'类目：酮康唑（OTC + RX）'});state.lines.filter(x=>!hasBoth||!isKet(x)).forEach(x=>chips.push({key:'line',value:x,label:`类目：${x}`}));if(state.sku)chips.push({key:'sku',label:`SKU：${state.sku}`});$('#activeFilters').innerHTML=chips.map(x=>`<button class="filter-chip removable" data-clear="${x.key}" data-value="${esc(x.value||'')}">${esc(x.label)}<b>×</b></button>`).join('');$('#filterCount').textContent=chips.length;$$('.filter-chip.removable').forEach(b=>b.onclick=()=>{if(b.dataset.clear==='shop')state.shop='all';if(b.dataset.clear==='ket')state.lines=state.lines.filter(x=>!isKet(x));if(b.dataset.clear==='line')state.lines=state.lines.filter(x=>x!==b.dataset.value);if(b.dataset.clear==='sku')state.sku=null;syncTree();refreshSkuTree();renderAll()})};
  const oldSync=syncUrl;syncUrl=function(){oldSync();const q=new URLSearchParams(location.search);if(state.categoryFocus)q.set('focus',state.categoryFocus);else q.delete('focus');history.replaceState({},'',`${location.pathname}?${q}`)};

  $('#ketoconazoleParent').onchange=e=>{KIDS.forEach(k=>{const box=leafChecks().find(x=>x.value===k);box.checked=e.target.checked});refreshSkuTree()};
  leafChecks().forEach(x=>x.onchange=()=>{syncTree();refreshSkuTree()});
  $$('[data-tree]').forEach(b=>b.onclick=()=>{leafChecks().forEach(x=>x.checked=b.dataset.tree==='all');syncTree();refreshSkuTree()});
  $('#skuSearch').oninput=refreshSkuTree;
  $('#applyFilters').onclick=()=>{state.shop=$('#shopFilter').value;state.lines=chosen();state.categoryFocus=KIDS.every(x=>state.lines.includes(x))?'酮康唑':null;state.sku=$('#skuFilter').value==='all'?null:$('#skuFilter').value;drawer(false);renderAll()};
  $('#resetFilters').onclick=()=>{state.shop='all';state.lines=[];state.sku=null;state.categoryFocus=null;$('#shopFilter').value='all';$('#skuSearch').value='';syncTree();refreshSkuTree();renderAll()};
  syncTree();refreshSkuTree();renderAll();
})();
